language: generic

os:
  - linux
  - osx

sudo: required

services:
  - docker

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull darktable/rawspeed; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew tap Homebrew/bundle && cd .ci && brew bundle --verbose; fi

env:
  global:
    - SRC_DIR=/build/rawspeed
    - BUILD_DIR=/build/rawspeed-build
    - INSTALL_PREFIX=/build/rawspeed-install
    - CFLAGS="-pipe" CXXFLAGS="-pipe"
    - TARGET=build
  matrix:
    - CC=cc CXX=c++
    - CC=cc CXX=c++ FLAVOR=Coverage

matrix:
  fast_finish: true
  include:
  - os: linux
    sudo: required
    services:
      - docker
    env: CC=clang-3.9 CXX=clang++-3.9
  - os: osx
    env: CC=gcc-6 CXX=g++-6

# linux clang Coverage build OOM's in gcov during final codecov report collection
# OSX gcc Coverage build produces invalid .gcno files

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mkdir "$TRAVIS_BUILD_DIR/build";
      docker run --read-only --volume $TRAVIS_BUILD_DIR:$SRC_DIR:ro --volume "$TRAVIS_BUILD_DIR/build":$BUILD_DIR --workdir $BUILD_DIR --tmpfs $INSTALL_PREFIX $EXTRA_TMPFS --env CC --env CXX --env CFLAGS --env CXXFLAGS --env SRC_DIR --env BUILD_DIR --env INSTALL_PREFIX --env TARGET --env FLAVOR darktable/rawspeed sh -c "$SRC_DIR/.ci/ci-script.sh";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export SRC_DIR="$TRAVIS_BUILD_DIR";
      export BUILD_DIR="$SRC_DIR/build";
      export INSTALL_PREFIX="$SRC_DIR/install";
      mkdir "$BUILD_DIR";
      mkdir "$INSTALL_PREFIX";
      "$SRC_DIR/.ci/ci-script.sh";
    fi

after_success:
  - export PLATFORM="$TRAVIS_OS_NAME";
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CXX=GCC;
    fi;
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export CXX=AppleClang;
    fi;
    cd "$TRAVIS_BUILD_DIR";
    curl -s https://codecov.io/bash > codecov;
    chmod +x codecov;
    ./codecov -e PLATFORM,CXX -F unittests;
